name: Retrain ML Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project
        run: mlflow run MLProject -P data_path=houseprice_preprocessing
