name: Retrain ML Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # 🧩 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 🧠 2. Setup Miniconda dan environment MLflow
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          python-version: 3.10
          auto-activate-base: false

      # 🔧 3. Install MLflow di environment
      - name: Install MLflow
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          pip install --upgrade mlflow

      # 🚀 4. Jalankan MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow run ./MLProject --env-manager=local -P data_path=houseprice_preprocessing

